spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rental_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
app:
  keycloak:
    timeout: 1000
    server-url: "http://localhost:9090"
    grant-type: "client_credentials"
    client-id: "auth_service"
    client-secret: "b3QgYhmy4p23nCFznMBhElwCz5BB6eLe"
    realm: "P2P-system"